re #2 Allow alternate AllowedCallersFilter to be used in JWTSecurityC…
NationalSecurityAgency/datawave-spring-boot-starter pull request #3
Opened 2020-10-07 19:47 UTC by billoley

…onfigurer

2020-10-08 18:58 UTC, ivakegg requested changes

2020-10-08 21:56 UTC, keith-ratcliffe commented on src/main/java/datawave/microservice/config/security/AllowedCallersFilter.java
> +            if (cert != null) {
Still trying to decide if we should be returning a 403, if enforcement is enabled and we hit the case where (cert == null). On the surface, it seems like we should raise a 403 but I'm on the fence, given that the code has always worked this way...and I'm unsure whether there are valid request contexts where those two conditions can be true

2020-10-09 13:10 UTC, keith-ratcliffe approved these changes

2020-10-13 18:01 UTC, billoley commented on src/main/java/datawave/microservice/config/security/AllowedCallersFilter.java
> +            filterChain.doFilter(httpServletRequest, httpServletResponse);
Consistent with how ProxiedEntityX509Filter.java and JWTAuthenticationFilter (which occur after AllowedCallersFilter) work
https://github.com/NationalSecurityAgency/datawave-spring-boot-starter/blob/master/src/main/java/datawave/microservice/authorization/jwt/JWTAuthenticationFilter.java#L74 shows the clearContext & setAttribute code for handling the same type of exception

2020-10-13 18:14 UTC, keith-ratcliffe approved these changes
Looks good

2020-10-14 12:31 UTC, merged