Update log4j in dependencies
NationalSecurityAgency/datawave-spring-boot-starter pull request #6
Opened 2021-12-20 17:42 UTC by alerman

2022-02-24 20:48 UTC, billoley approved these changes

2022-02-25 15:00 UTC, ivakegg submitted a review, later dismissed

2022-03-03 19:35 UTC, jwomeara requested changes
An alternative way to handle this would be to update the datawave service parent with these changes since that casts a much wider net w.r.t. all of our microservices and submodules.  

The feature/spring-boot-2.4 branches all have these changes, but who knows when those lazy devs will finish that work...  ;)

2022-03-03 19:35 UTC, jwomeara commented on pom.xml
> +                <version>2.17.1</version>
Consider adding this as a property.

2022-03-04 14:48 UTC, billoley approved these changes

2022-03-04 16:22 UTC, ivakegg approved these changes

2022-03-04 16:24 UTC, merged